---

- name: Configure nginx
  block:
    - name: selinux disable permanently
      selinux:
        policy: targeted
        state: permissive

    - name: set in permissive without reboot
      command: setenforce 0
      ignore_errors: true
      changed_when: false

    - name: update nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
      notify:
        - reload nginx
