---

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open ports firewall
  firewalld:
    zone: public
    port: '{{item}}'
    permanent: true
    state: enabled
  loop:
    '{{open_ports}}'
  notify:
    - reload firewall